### PR TITLE
Release v1.0.1

### PR DESCRIPTION
**Pull request by accuminium**
Please let us all come to an agreement about this patch release before we merge and create the release tag. That is, let's make sure that all submodules are at the point they should be and that we have no issues and PRs on this repo that we want to make part of v1.0.1.

For instance, I suggest we take #19 into v1.0.1 and then maybe make this release v1.1.0, since it's not a patch but an enhancement/extension.

### CODE REVIEW

**Comment by alessandrocapotondi** [comment]
@accuminium for me you can merge it when you want.

**Comment by alessandrocapotondi** [comment]
I added the CHANGELOG to the `hero-gcc-toolchain`

**Comment by alessandrocapotondi** [comment]
Ciao @accuminium, @vogelpi, on my side we have a green light for the release.
I merged PR on the hero-gcc-toolchain and libhero-target repos. I also create CHANGELOG for both the repos.

**Comment by accuminium** [comment]
Thanks for your updates, @alessandrocapotondi.  I squashed your commits into the existing one and updated the branch.

Let's also include v1.0.1 of `hero-openmp-examples` once that's ready ([PR currently up for discussion](https://github.com/pulp-platform/hero-openmp-examples/pull/11)).

One comment about hero-gcc-toolchain: In this release, that submodule points to a commit that is not a tag. We should avoid that as soon as we use #25, because it will cause problems with downloading artifacts.

**Comment by accuminium** [comment]
Thanks for your feedback! I will merge this and release `v1.0.1-rc1`, which we can put through some extra tests tomorrow before tagging `v1.0.1`.

**Pull request merged**
