### PR TITLE
Release v1.0.1-rc2

### PR DESCRIPTION
**Pull request by alessandrocapotondi**
Added sobel-filter application

### CODE REVIEW

**Comment by alessandrocapotondi** [comment]
@vogelpi @accuminium,

the only branch which is under CI is at the moment the `integration` branch. If we would continue to use it we should keep such branch aligned with the candidate release that we want to merge on  'master'

**Comment by accuminium** [comment]
Ciao @alessandrocapotondi, thanks for the update. I took the liberty of changing your commit so that the existing line on `hero-openmp-examples` in the Changelog is updated instead of adding a new line that contradicts (in the version number) the existing one. Let's merge after the call today.

**Comment by alessandrocapotondi** [comment]
> Ciao @alessandrocapotondi, thanks for the update. I took the liberty of changing your commit so that the existing line on `hero-openmp-examples` in the Changelog is updated instead of adding a new line that contradicts (in the version number) the existing one. Let's merge after the call today.

I am fixing the problem right now

**Comment by accuminium** [comment]
I already did the rebase and squash, so you can just do a regular merge and tag :-)

**Pull request merged**
